### ISSUE TITLE
new day

### ISSUE THREAD

**Issue by sonyanariman** [mdn/learning-area#713]
```[tasklist]
### Tasks
- [ ] https://github.com/mdn/learning-area/pull/480
- [ ] https://github.com/mdn/learning-area/pull/712
- [ ] https://github.com/mdn/learning-area/pull/649
```
